import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/sidebar/Sidebar";
import Header from "@/components/header/Header";
import Image from "next/image";
import backImg from "../../public/images/image.png";
import ProtectedImage from "@/components/Image";
import AppLayout from "@/components/AppLayout";
import NotificationCustom from "./NotificationCustom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Store Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <NotificationCustom>
          <AppLayout>{children}</AppLayout>
        </NotificationCustom>
        <ProtectedImage />
      </body>
    </html>
  );
}
