import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import ProtectedImage from "@/components/Image";
import AppLayout from "@/components/AppLayout";
import NotificationCustom from "./NotificationCustom";
import GeneralModalProvide from "@/components/modal/GeneralModalProvide";
import {ThemeProvider} from "@/components/ThemeProvider";
import TooltipProvider from "@/components/tooltip/TooltipProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Store Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="body">
        <ThemeProvider>
          <TooltipProvider>
            <GeneralModalProvide>
              <NotificationCustom>
                <AppLayout>{children}</AppLayout>
              </NotificationCustom>
              <ProtectedImage />
            </GeneralModalProvide>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
